name: ramp-human-locomotion
channels:
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn

  # Extra requirements
  - tensorflow
  - keras
  - pytorch
  - scipy
  - lightgbm
  - pip
  - pip:
    - ramp-workflow
    - osfclient
    - scikit-multilearn
    - python-louvain
    - gudhi
    - xgboost
    - catboost
