name: ramp-human-locomotion
channels:
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - scikit-learn

  # Extra requirements conda
  - tensorflow
  - keras
  - pytorch
  - scipy
  - lightgbm

  - pip
  - pip:
    - ramp-workflow
    - osfclient

    # Extra requirements pip
    - scikit-multilearn
    - python-louvain
    - gudhi
    - xgboost
    - catboost
